FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY bot.py .

ENV TELEGRAM_TOKEN="<your-bot-token>"
ENV ADMIN_ID="<your-admin-id>"

CMD ["python", "bot.py"]
